version: 1.0.{build}
branches:
  only:
  - master
  - development
  - ^version-.*$
image: Visual Studio 2019 Preview
configuration: Release
clone_depth: 1
build:
  project: MyTested.AspNetCore.Mvc.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "samples/MusicStore/MusicStore.Test/MusicStore.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Blog/Blog.Test/Blog.Test.csproj" --configuration Release --no-build