version: 1.0.{build}
branches:
  only:
  - master
  - development
  - ^version-.*$
image: Visual Studio 2019 Preview
configuration: Release
clone_depth: 1
before_build:
- cmd: dotnet restore
build:
  project: MyTested.AspNetCore.Mvc.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "samples/MusicStore/MusicStore.Test/MusicStore.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Blog/Blog.Test/Blog.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/ApplicationParts/ApplicationParts.Test/ApplicationParts.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.AssemblyInit.Test/Autofac.AssemblyInit.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.NoContainerBuilder.Test/Autofac.NoContainerBuilder.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.Test/Autofac.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.Core.MissingAppPackage/Test.Core.MissingAppPackage.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.DifferentEnvironment/Test.DifferentEnvironment.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.ExplicitNoStartupType/Test.ExplicitNoStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.FullFramework.NoCompilationContext/Test.FullFramework.NoCompilationContext.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.MissingStartupType/Test.MissingStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.NoAsync/Test.NoAsync.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.NoStartupType/Test.NoStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongStartupType/Test.WrongStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongTestAssembly/Test.WrongTestAssembly.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongWebAssembly/Test.WrongWebAssembly.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/FullFramework/FullFramework.AssemblyInit.Test/FullFramework.AssemblyInit.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/FullFramework/FullFramework.Test/FullFramework.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Lite/Lite.Test/Lite.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/NoStartup/NoStartup.Test/NoStartup.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/WebStartup/WebStartup.Test/WebStartup.Test.csproj" --configuration Release --no-build
