language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libunwind8
mono: none
os:
- linux
- osx
osx_image: xcode8.2
branches:
  only:
  - master
  - development
  - ^version-.*$
script:
- ./build.sh