language: csharp
sudo: required
dist: trusty
dotnet: 2.1.700
solution: MyTested.AspNetCore.Mvc.sln
mono: none
os:
- linux
- osx
osx_image: xcode9.4
branches:
  only:
  - master
  - development
  - ^version-.*$
script:
  - dotnet test -c Release -f netcoreapp2.1